#version: '7.2.0.{build}'

environment:
  CMAKE_PATH: $(APPVEYOR_BUILD_FOLDER)\cmake-3.4.1-win32-x86
  VS_VERSION: "Visual Studio 14"
  priv_key:
    secure: o18/sShy+YYAoetfFCxSIvs29CQGOFXOJxCQ4G3vVZwXjDPkJJQdjMZVEpAnH2sUlrZi6XDKv00neJIVrc1777jAkzSegDrQlMe/0Q5CGxghaEr+/74I9xIOx6d61gJrCji1yCJvE2oFBnnht6AXeu7OeBU786vH2vDOcseUGoSsdk2M0AF79iTYyJyIiayQEvsqnhTMz8Ab5JVhjwFVU/PBEPpFJtFrxLg+ze8VhiXymMxPyKb+BpW5uJW3dubi5e/pQ54mojHXuQ74+tNHcsrfxo5RkxYIUrdDw0BdxJlyRz/MbCAkp4SfIDMgGZiffHL1JcQfG+IEcD81H1Q7nbKM3FiFwgVAMkSqfuIsIDGJJEI76y9qEZ1UlR/YMQ3hQPgYIeYQAC35e2Ye+pOdzwTTiCq1YrOf8cI19bvbfOiDRkvu7qQs623ml/znH5XeJJi1CN45j17yfjviKjn7092oYKqw2Shja+jjfsE/ZJjGaq9bEiHuUQPsQLW5LLHcsMk6NTW+aPr8QirI6lkyvKG707r18hh/Lby9AUvnjPMtKwAMje1kw+++nx/7V2XWYe8WWeb1AjM652eYt4B+Xg1VARR4FevHMJaAhYPwcuqAW6LYGTJqfg0X6fogeivFZAefBGFHTazWLa0AAXBi2R+NadnAOYpCE+/7NmngnKXuX1rp3MdyG+NfA2Q/wO5/5/ABTiuZmF3IoerQLL+Qw2U+W4iXbczmSykJR5KT/l5B2Jjc5tEu07hY8jY098eS7YXr1TBYiuDdB9q97+hLPWCB5njy9aZPSTen2L/2vew9aHa9zVlXSJ1QAytj8rqbuvu7sSiDfxJc258HU6+JMEkBrGw+L15KX5uK0SFtPKHf70joHUDtb9zaXyibFICkRmzPThW15TEYCpocnAh6VJDzfRZHLeAF54dTm00Eh6kHU5S6k009Vl5v8KHTXcnYSikbDyyvzNP3ZQqOTkVmNfJPUgiAbmaPuL5H9NMc0q8bfbn1rUjg9vDMtu/oPgCeVcDIdUaj/xkv2jzdBkY+9gHVi9hQuat3sCUx/FTmyiUCz8+59GcbjC9IvebCvZ/bkJ6UEHcguu4x2GeF8L4mp9GUB42rxX2tVDu+7r1iGwQY1AG6IzrC5Lat24Ydra32kd5cbeLBptsqBXTWXn/NUdTYIdikpOgDGu9g5/i+W5+Q1ymof98U3QpmcbdBFfG9yqIHq/lFyBUAue4hD+nPOF9jj4xV5SAidOBtf8kBjHiU/C+yjaD4vxmI6H6RoZCxsO/wObFnNGTPOGuf/tAv7HJi2NQgFnOtP/5WrE44aCfpnXw3INRE00gKXPNbGOJe46ZGUm5n3H2lGUUn2tcYzCgRcwoVY2LqlaK/K2CCsc/L3TimyUYHWN6DcYgezfOXvaG5UnlefnCOOv4CZJ9IFRdQeuxmoFFNfzOiINaTLJpatiI64yBMvXiChBYEIk170t7PyrPsAIxrqm2BcJqyR3O7HiwAUaq8iKPB4+52FUwbK7vV64gPikquAbgKImGp0LoYl5+Bb6VYb+CVTpHMqwyelCo8aOlhs3u/s7zVeR004myG+4gN5u58zY2zcAPYW0ObWm7tGZD8zQSpMRq+rYsIF0BH161Sr9CJbvY5OuzokLh4/a8VsX1rAUoG+TIEOYzN0+rYl400duAkni3QVDaCOH/+tCb92/+y9jFzM8jczk0Rf7nNKsoIhGRV2jy0r1qZb0IFr80OseKXEDZI2WmaWuIiQYGTzpoNdAo3rYAh4t8s7HnJb0bgB7oI5ANFEzcEtiI6mOwPKey57ECd3VMDQv6sfKUCKdQjyVPuOUWiqfzvToLT32dFVMzM6+3vQ/sFbq72Gh12PLSVinoZ7ldaERKUo+brrErhd8Ilxx91Ld5qple1nCeFCgaAGwtnx+1ce/xw1lhCMwdRopg67aOE7MIsx1IryiElFijDU3+VmPTjcowfzzvr+U0wRWNxw6uv8761kXy/tKLwdBEFSfu18n855P1zPSoo/z98/ezPx9zSHfLj0ogI7V2OqY8vaI9MpMBslEB2ADpaFxHGP0pbSGCsG6ecA5+UJDB1nbL5iS0DrDUgMdguobMJ7BcGOBZw7HvEyxtcaf+iLwyU74rLKEFQmG9KKr/U7ZqheHQLTtVRFxfsxFGvBbJxRWSw2X+ZZHnBYhbISbogvZ2M2rQGAj7e/xNcqNZMZiILCdQWVH2avAWzKDMuMBbJ4PgASFTpqQJBasPuxuJdGr4KLLZHMp/0PS4rNgawkpD3fZyWQTCs59sbZdXrQGBwrcDNzrCPLe/vpLKZNTvyOUFxdBlQRYbVjOI1yKujnihp3RdqMOrqU71Zjh4qIPOENvXnSMA6Roy+MJk8id09eg3mD7SQ4gxJVz+CtLaZv+q45rmcbP8h4Jhi/QKMomorLzLg3HHqx0/UaVayMT8CZv/kuOHUHLTKdOzxH9cyiEswOU6hao89PCr3r2vvitBAf72ct/NHkCFLUuDeZZaYhKmjkE/YFyYxcM1cm75csx/vBF3B+R+oP6P3uz8JcSBZrGVPdDXpzmE7lzssfOCpgIslsf7HocFjsxPPNFZ4PNygZlzxxM7P4Z9Zv5qjSPkAFMVahZeOu/wekmZhvflm25/ZLhn8mIqfI/TQ4SvYHh+S8VBUowerwlmoT2t1RUQeBQnabMAtwvxh99ITqZ81N+ifYk72IC7nt+3n+uNrTtK483xus3WiBVtV4HhDOSndbx7fjVtFzLcpgxJ6BrJFvQtZsAfs7te4sMGZrlhiuxGUe47Plf1qDSGTd5hkMKbvoCsjHv8Z2RZLHNcdJYG05WV7IrcL67GV/3mBLHKax2tPQkn6U5RqHf9Aud0VGIzSWls9dC7lcTtgPQHxVC4kOVuHgaZAHH1T97AiJeFBno6vFj0aOviMdKlFtWb40Izh9NDyRyjBeM1zhlCy/szIMFW+oumPC56O/tTIh3IL1G7fRhWIsScmzMTbrk3b6LDLXQ/fkUTc9jxF6Ptm5vHZv+sbEdQE/EQHcMCB5BU/UfmpS5sOJY3i26JZwUT8M73X60PSb/TDYnUO+o771IVOBQJOs4z2FOv+OSaM4a0UAz0bYOVqhuh4/sErtAkR51R/Ojdu9XbF9F+Ms9tfF3CZd331RooKNvtMPrXaDWmy7eMInMKjCI0ReUyLOpyV/a6yhDmKcuh8HjdE0roniFYBGhiazpXaYorLA0AgdIxoW83QCkOY9Ck4NlLsswIpm29Rzej0rtdON1QlPqxhMVtJav6MDlbPNmD+0+fLhGWXbdIGIB5sMXb8yMkcmIKHA3xmrc8RhRPS3aBq24C7dPdWD8ti0klXEZAOOQ4XtsvDiNalBz9lRvMuY4crGjuu8Rkif+zPQ0FVyHoBk/PzP3G6/XfIVBIoT4doYkG/1yjGXYT9NnT4e+Vv0iEqjSJsie7aquMYd5dZNlv3CiZHCmxp5e3RoXiCZEizvHVbAnSHLlgX4MJoelv98Z04zhIKiB14Ydmr2HFn/2QwTWBcuvlLix8lwQk3CjIPCMLxsGQPrHBNkpH/lYf4O6hOTbltxLEUMyjEMvH/9ZvSA8nTHrO1oVg8XxHE+k1o1zcS9qzgVSscqhYs+mJdaslqZEd0SSSyEb2Dn1634XnBce+WB7Os27eD/SJIIppPshmSxAWm2qp0C2shaCF2cW9CsoWcrQj78CMyoSOVZRxf/iV9QgkrTDwDtSUfl6lLRdwdC17mA6pLfvjV6x5ttjvKfy0slqzJFu/BDwJZUEl3cjxcH4u3kab99R9cdISWcaFyzzaxIgy9U2jOnMvchiOychN3WZGRGnlBFHcBk/4dEfmHVLAp10Yat0ZmKoRckmdp1e9OF/McNLemclvOYL3NZ9weAdrDMIyYXQPunihJ/Db5V0pQ5Ayqef7+iYvESI0AHLlWYgpEaeNLilxVuEE6U9uLRNvkpd634Jmzld/+UsLvcIQ+A3mHCPJrR3YxTKBA/acFPv7iFvrNTIaCcadR35uTb21jQg+hld6pOH3j6gszslgVOdZh9Ey97Atvm9H/pnogNqES+YzETDKlHvTch9Z5RI1xTUJLflnePbBLGnsLbpVotcVe9snED8DFy7/mwpX8d3SpvqKeiNWRdrvu72lZ7NnGCrIs6tpU8BweNIXAwRibtxu6BZSQwBWt+jMqqPpSOyZrpbCd5XAZi5YzWQ3oKe7hBmgQ4GL5Pty6nawzL5sn74BZs7Jjsilk0drkneMILAM0ono=
configuration: Release
shallow_clone: false

platform:
  - x86
  - x64

install:
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
  - git submodule update --init --recursive
  
build_script:
  - if "%platform%" == "x86" SET VS_FULL=%VS_VERSION%
  - if "%platform%" == "x86" SET CUSTOM_FLAG=""
  - if "%platform%" == "x64" SET VS_FULL=%VS_VERSION% Win64
  - if "%platform%" == "x64" SET CUSTOM_FLAG="-DWIN64:Bool=True"
  - mkdir build
  - cd build
  - cmake -G "%VS_FULL%" %CUSTOM_FLAG% .. > %APPVEYOR_BUILD_FOLDER%\configure.log			
  - cmake --build . --config Release > %APPVEYOR_BUILD_FOLDER%\build.log
  - cd ..
  - mkdir %APPVEYOR_PROJECT_NAME%
  - cp -r externals %APPVEYOR_PROJECT_NAME%
  - cp -r help %APPVEYOR_PROJECT_NAME%
  - cp License.md %APPVEYOR_PROJECT_NAME%
  - cp ReadMe.md %APPVEYOR_PROJECT_NAME%
  - 7z a %APPVEYOR_PROJECT_NAME%-win-%platform%.zip %APPVEYOR_PROJECT_NAME% > %APPVEYOR_BUILD_FOLDER%\archive.log

test_script:
  - cd build
  - ctest -C Release . -V

artifacts:
  - name: Build
    path: '*.zip'
  - name: Log files
    path: '*.log'
